### ISSUE TITLE
Explain how to add a new entry

### ISSUE THREAD

**Issue by wetneb** [DougInAMug/Collective-Governance-Directory#7]
It would be nice to have some instructions for people who want to submit a new entry. I would put it in the about page and/or the readme.

**Comment by DougInAMug** [comment]
I just:
- added a section on contributing on the about page: https://collectivegovernance.directory/about#contributing
- update the readme: https://github.com/DougInAMug/Collective-Governance-Directory

Do you think those changes are good enough to close this issue for now?
