### ISSUE TITLE
Add continuous integration / continuous deployment

### ISSUE THREAD

**Issue by wetneb** [DougInAMug/Collective-Governance-Directory#8]
When opening a pull request like https://github.com/DougInAMug/Collective-Governance-Directory/pull/6, it could be nice to have a job (such as a GitHub Actions workflow) which would check that the site compiles correctly. For instance this would catch JSON formatting errors.

Also the deployment pipeline could be improved: gerenally, the build artifacts (your `build/` directory) are not tracked in the Git repository, but are generated when deploying.

**Comment by DougInAMug** [comment]
I just moved the build step to the workflow and took `build/` out of the repo This seems to catch big JSON formatting errors, but not 'smaller' ones (e.g. incorrectly naming a key leading to `undefined` in the web app). This seems 'OK', but if you have a further suggestion for error checking, let me know! Else feel free to close.

**Comment by wetneb** [comment]
Amazing! That looks much better. To catch such additional errors, you could add some tests to your app and run them from the CI. For instance, one test could validate the JSON blob against a [JSON Schema](https://json-schema.org/).
